version: '3.8'

services:
  redis-master:
    image: redis:7.2
    container_name: redis-master
    volumes:
      - ./redis-master.conf:/tmp/redis-master.conf
    command: redis-server /tmp/redis-master.conf
    ports:
      - "6379:6379"
    networks:
      - redis-cluster

  redis-slave-1:
    image: redis:7.2
    container_name: redis-slave-1
    volumes:
      - ./redis-slave.conf:/tmp/redis-slave.conf
    depends_on:
      - redis-master
    command: redis-server /tmp/redis-slave.conf
    ports:
      - "6380:6379"
    networks:
      - redis-cluster

  sentinel-1:
    image: redis:7.2
    container_name: sentinel-1
#    environment:
#      - SENTINEL_ANNOUNCE_IP=sentinel-1
    volumes:
      - ./sentinel.conf:/tmp/sentinel.conf
      - sentinel-1-data:/data
    restart: always
    depends_on:
      - redis-master
    command: sh -c "sleep 20 && cp /tmp/sentinel.conf /data/sentinel.conf && redis-sentinel /data/sentinel.conf"
    ports:
      - "6381:26379"
    networks:
      - redis-cluster

  sentinel-2:
    image: redis:7.2
    container_name: sentinel-2
#    environment:
#      - SENTINEL_ANNOUNCE_IP=sentinel-2
    volumes:
      - ./sentinel.conf:/tmp/sentinel.conf
      - sentinel-2-data:/data
    restart: always
    depends_on:
      - redis-master
    command: sh -c "sleep 30 && cp /tmp/sentinel.conf /data/sentinel.conf && redis-sentinel /data/sentinel.conf"
    ports:
      - "6382:26379"
    networks:
      - redis-cluster

  sentinel-3:
    image: redis:7.2
    container_name: sentinel-3
#    environment:
#      - SENTINEL_ANNOUNCE_IP=sentinel-3
    volumes:
      - ./sentinel.conf:/tmp/sentinel.conf
      - sentinel-3-data:/data
    restart: always
    depends_on:
      - redis-slave-1
    command: sh -c "sleep 30 && cp /tmp/sentinel.conf /data/sentinel.conf && redis-sentinel /data/sentinel.conf"
    ports:
      - "6383:26379"
    networks:
      - redis-cluster
networks:
  redis-cluster:
    driver: bridge
volumes:
  sentinel-1-data:
  sentinel-2-data:
  sentinel-3-data:
